name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync
      - run: uv run mypy proton_cli
      - run: uv run ruff check
      - run: uv run pytest
      - run: uv build
